name:     choose
version:  1.0.0.0
category: Random

synopsis: >
  Choose random elements from a stream.

description: >
  Provides an efficient mechanism to select /n/ items uniformly
  at random from an input stream, for some fixed /n/.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license:      Apache-2.0
license-file: license.txt

ghc-options: -Wall
default-extensions:
  - CPP
  - DeriveFunctor
  - InstanceSigs
  - RankNTypes
  - ScopedTypeVariables

dependencies:
  - base
  - containers
  - MonadRandom
  - semigroups
  - streaming
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Data.Random.Choose

tests:
  test:
    source-dirs: test
    main: test.hs
    dependencies:
      - base
      - checkers
      - choose
      - HUnit
      - QuickCheck
      - test-framework
      - test-framework-hunit
      - test-framework-quickcheck2
    ghc-options: -Wall -fno-warn-orphans
