name: choose
version: 0.1.0.0
synopsis: Choose random elements from a stream.
description: >
  Provides an efficient mechanism to select /n/ items uniformly
  at random from an input stream, for some fixed /n/.
author: Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>
license: Apache-2.0
license-file: license.txt
category: Random
ghc-options: -Wall -fwarn-unused-imports

dependencies:
  - base >= 4.7 && < 5
  - MonadRandom

library:
  source-dirs: .
  exposed-modules:
    - Data.Random.Choose
    - Data.Random.Choose.Tree
    - Data.Random.Choose.IO
