name: choose
version: 0.1.0.0
license: Apache-2.0
category: Random
ghc-options: -Wall -fwarn-unused-imports

dependencies:
  - base >= 4.7 && < 5
  - MonadRandom

library:
  source-dirs: .
  exposed-modules:
    - Data.Random.Choose
    - Data.Random.Choose.Tree
    - Data.Random.Choose.IO
