name: choose-exe
version: 0.1.0.0
license: Apache-2.0
license-file: ../license.txt
category: Application
ghc-options: -Wall -fwarn-unused-imports

dependencies:
  - base >= 4.7 && < 5
  - choose
  - optparse-applicative
  - text

library:
  source-dirs: .
  exposed-modules:
    - Data.Random.Choose.Executable
    - Data.Random.Choose.Executable.Args

executables:
  choose:
    source-dirs: .
    main: choose.hs
