name:     choose-exe
version:  0.1.0.0
category: Application

synopsis: >
  Command-line program to choose random element from a stream.

description: >
  A command-line program that reads lines from stdin and outputs
  some fixed number of them, selected uniformly at random.

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

license:      Apache-2.0
license-file: license.txt

ghc-options: -Wall

dependencies:
  - base
  - choose
  - optparse-applicative
  - text

library:
  source-dirs: .
  exposed-modules:
    - Data.Random.Choose.Executable
    - Data.Random.Choose.Executable.Args

executables:
  choose:
    source-dirs: .
    main: choose.hs
